services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./data:/app/database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/database/club_signup_form.db
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.community.dialect.SQLiteDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    command: ./mvnw spring-boot:run